apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: 975050133565.dkr.ecr.ap-northeast-2.amazonaws.com/pet-connect-main
    newName: 975050133565.dkr.ecr.ap-northeast-2.amazonaws.com/pet-connect-main
    newTag: "PLACEHOLDER"  # 여기에 GitHub Actions에서 자동으로 새로운 태그가 설정됩니다.
resources:
  - ../../base
patchesStrategicMerge:
  - main-deployment-patch.yaml
  - main-service-patch.yaml

