apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 975050133565.dkr.ecr.ap-northeast-2.amazonaws.com/pet-connect-main
  newName: 975050133565.dkr.ecr.ap-northeast-2.amazonaws.com/pet-connect-main
  newTag: 3f6b6c01
resources:
- ../../base
patchesStrategicMerge:
- main-deployment-patch.yaml
- main-service-patch.yaml
