apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-connect-main-deployment
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: pet-connect-main-fargate
  template:
    metadata:
      labels:
        app: pet-connect-main-fargate
