apiVersion: v1
kind: Service
metadata:
  name: pet-connect-main-service
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
  labels:
    env: dev
spec:
  selector:
    app: pet-connect-main
