apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-pet
  region: ap-northeast-2
fargateProfiles:
  - name: main-eks-fargate-profile
    selectors:
      - namespace: default
        labels:
          app: pet-connect-main
