apiVersion: v1
kind: Service
metadata:
  name: pet-connect-main-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: pet-connect-main
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
